baseURL = "https://hanyu.cool/techblog/"
languageCode = "zh-cn"
title = "韩西瓜 | 我要喝啤酒 "
theme = "KeepIt-master"
summaryLength = 70
hasCJKLanguage = true


enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""
disqusShortname = "yourdiscussshortname"

paginate = 6

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"


[params]

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  
    since = 2021
    author = "韩西瓜"               # Author's name
    subtitle = "嘿，朋友，我是韩西瓜，一名Developer，目前就职于腾讯，欢迎关注公众号「韩西瓜」,期待和你遇见呀"       # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "post" # post or other

    google_verification = ""
    bing_verification = ""
    yandex_verification = ""
    pinterest_verification = ""
    baidu_verification = ""

    avatar = "https://file.hanyu.cool/site/home/static/v1/img/avatar.jpeg" #comment it to use gravatar
    socialShare = true

    description = "" # site description
    keywords = "" # site keywords

    license= 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.gravatar]
    #email = "example@gmail.com"   #uncomment and insert your email address to use gravatar


[params.social]
    GitHub = "okhanyu"
    #Linkedin = "#"
    #Twitter = "#"
    #Instagram = "#"
    Email   = "hanyu@hanyu.cool"
    #Facebook = "#"
    #Telegram = "xxxx"
    #Medium = "xxxx"
    #Gitlab = "xxxx"
    #Youtubelegacy = "xxxx"
    #Youtubecustom = "xxxx"
    #Youtubechannel = "xxxx"
    #Tumblr ="xxxx"
    #Quora = "xxxx"
    #Keybase = "xxxx"
    #Pinterest = "xxxx"
    #Reddit = "xxxx"
    #Codepen = "xxxx"
    #Bitbucket = "xxxx"
    #Stackoverflow = "xxxxx"
    Weibo = "sohanyu"
    #Odnoklassniki = "xxxx"
    #VKontakte = "xxxx"
    #Flickr = "xxxx"
    #Xing = "xxxx"
    #Snapchat = "xxxx"
    #Soundcloud = "xxxx"
    #Spotify = "xxxx"
    #Bandcamp = "xxxx"
    #Paypal = "xxxx"
    #Fivehundredpx = "xxxx"
    #Mix = "xxxx"
    #Goodreads = "xxxx"
    #Lastfm = "xxxx"
    #Foursquare = "xxxx"
    #Hackernews = "xxxx"
    #Kickstarter = "xxxx"
    #Patreon = "xxxx"
    #Steam = "xxxx"
    #Twitch = "xxxx"
    #Strava = "xxxx"
    #Skype = "xxxx"
    #Whatsapp = "xxxx"
    Zhihu = "okhanyu"
    Douban = "#"
    #Angellist = "xxxx"
    #Slidershare = "xxxx"
    #Jsfiddle = "xxxx"
    #Deviantart = "xxxx"
    #Behance = "xxxx"
    #Dribble = "xxxx"
    #Wordpress = "xxxx"
    #Vine = "xxxx"
    #Googlescholar = "xxxx"
    #Researchgate = "xxxx"
    #Mastodon = "xxxx"
    #Thingiverse = "xxxx"

[params.share]
#Twitter = true
#Facebook = true
#Reddit = true
#Linkedin = true
#Pinterest = true
#HackerNews = true
#Mix = true
#Tumblr = true
#VKontakte = true
#Douban = true
Weibo = true

# Used only for Seo schema
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[author]
  name = "韩西瓜"

  [params.publisher]
    name = "韩西瓜"

  [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40

  [params.logo]
    url = "logo.png"
    width = 127
    height = 40

  [params.image]
    url = "cover.png"
    width = 800
    height = 600

[params.gitalk]
owner = ""       # Your GitHub ID
repo = ""        # The repo to store comments
clientId = ""    # Your client ID
clientSecret = "" # Your client secret

[params.valine]
  enable = false
  language = 'en'
  appId = 'your appId'
  appKey = 'your appKey'
  notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
  verify = false # Verification code
  avatar = 'mm'
  placeholder = 'your comments ...'
  visitor = true

[params.utterances]       # https://utteranc.es/
    owner = ""              # Your GitHub ID
    repo = ""               # The repo to store comments

[params.gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
    owner = ""              # Your GitHub ID
    repo = ""               # The repo to store comments
    clientId = ""           # Your client ID
    clientSecret = ""       # Your client secret

[menu]
  [[menu.main]]
    identifier = "nav"
    name       = "Nav"
    url        = "../"
    weight     = 1
  [[menu.main]]
    identifier = "Home"
    name       = "Home"
    url        = "/"
    weight     = 2
  [[menu.main]]
    identifier = "Post"
    name       = "Posts"
    url        = "/posts/"
    weight     = 3
  [[menu.main]]
    identifier = "Categories"
    name       = "categories"
    url        = "/categories/"
    weight     = 4
  [[menu.main]]
    identifier = "Tags"
    name       = "Tags"
    url        = "/tags/"
    weight     = 5
  [[menu.main]]
    identifier = "About"
    name       = "About"
    url        = "/about/"
    weight     = 6